// Run with node tests/web/test_project_library.cjs. No browser or native app required.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const elements = new Map();
function $(selector) {
    if (!elements.has(selector)) elements.set(selector, {value: '', content: ''});
    const item = elements.get(selector);
    const api = {};
    for (const method of ['show', 'hide', 'toggleClass', 'removeClass', 'addClass', 'empty', 'prop']) api[method] = () => api;
    api.html = value => { if (value === undefined) return item.content; item.content = value; return api; };
    api.text = api.html;
    api.attr = (name, value) => { if (value === undefined) return item[name]; item[name] = value; return api; };
    api.val = value => { if (value === undefined) return item.value; item.value = value; return api; };
    return api;
}
const context = { $, console, Date, window: {}, document: {}, navigator: {},
    SendWXMessage: () => {}, OutputKey: (...args) => context.keys.push(args), keys: [] };
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../../resources/web/homepage/js/library.js'), 'utf8'), context);
const item = (name, folder, extra = {}) => ({ name, path: folder + '\\' + name + '.3mf',
    folder, root: 'E:\\Projects', group: folder.split('\\').pop(), kind: '3mf', state: 'prepped', mtime: 10, ...extra });
const alpha = item('Alpha', 'E:\\Projects\\Props');
const beta = item('Beta', 'E:\\Projects\\Signs', { superseded: true });
context.PROJECT_LIBRARY = {items: [alpha, beta], roots: ['E:\\Projects']};
context.LibNoteRecent([{path: 'e:/projects/Props/Alpha.3mf'}, {path: beta.path},
    {path: 'D:\\Downloads\\Outside.3mf'}, {path: 'D:\\Downloads\\Outside.3mf'}]);
const paths = () => Array.from(context.LibFiltered(), record => record.path);
context.LIB.state = 'recent';
context.LibSearch('Alpha');
assert.deepEqual(paths(), [alpha.path], 'Recent search must not resurrect filtered records as unindexed');
context.LibSearch('');
context.LibSetGroup('Signs');
assert.deepEqual(paths(), [beta.path], 'Recent group filter must be respected, including formerly superseded files');
context.LibSetGroup('all');
assert.equal(paths().length, 3, 'Recent aliases and duplicate records must collapse');
assert.equal(context.LibFiltered()[0].state, 'prepped', 'Normalised recent retains indexed metadata');
context.LibSearch('Downloads Outside');
assert.deepEqual(paths(), ['D:\\Downloads\\Outside.3mf'], 'Unindexed recents must still be searchable by folder');
context.LibSearch('nothing-matches');
assert.equal(paths().length, 0);
context.LibResetFilters();
assert.equal(paths().length, 3, 'Unrelated files must not disappear because legacy folder inference marked them superseded');
assert.equal(context.LibKey('file:///E:/Projects/A%20B/%23test.3mf'), context.LibKey('e:\\Projects\\A B\\#test.3mf'));
assert.equal(context.LibKey('E:\\Projects\\Props\\..\\Signs\\Beta.3mf'), context.LibKey(beta.path));
assert.equal(context.LibDate(0), '', 'Unknown recent timestamp must not display 1970');
let prevented = false;
context.LibKeyboard({target: {tagName: 'INPUT'}, keyCode: 65, ctrlKey: true, preventDefault() { prevented = true; }});
assert.equal(prevented, false, 'Search owns Ctrl+A and typing');
context.LibKeyboard({target: {tagName: 'BODY'}, keyCode: 78, ctrlKey: true, shiftKey: true, preventDefault() { prevented = true; }});
assert.equal(context.keys.length, 1, 'A modified shortcut must be forwarded exactly once');
context.LibNoteRecent([]);
context.LIB.state = 'recent';
assert.equal(paths().length, 0, 'Clearing recents must immediately empty the filter');
context.LibReceive({native: true, items: [alpha], roots: ['E:\\Projects'], rootStatus: [
    {path: 'E:\\Projects', count: 1, error: ''}, {path: 'Z:\\Missing', count: 0, error: 'Folder unavailable'}], generated: 1});
assert.match(elements.get('#LibFoldersList').content, /Folder unavailable/);
assert.match(context.LibCard({...alpha, name: '<script>', folder: 'E:\\A & B'}), /&lt;script&gt;/);
assert.match(context.LibCard(alpha), /Open folder/);
const tactile = item('Tactile tile', 'E:\\Projects\\Tactile', {kind: 'stl', path: 'E:\\Projects\\Tactile\\tile.stl'});
const downloaded = item('Downloaded', 'E:\\Models\\Tactile', {root: 'E:\\Models'});
context.PROJECT_LIBRARY = {items: [tactile, downloaded, alpha], roots: ['E:\\Projects', 'E:\\Models']};
context.LIB_WORKSPACE = {mine: [{path: 'E:\\Projects\\Tactile', title: 'Tactile work'},
    {path: 'E:\\Projects\\CAD only', title: 'CAD only'}], downloads: ['E:\\Models'], jobs: ['E:\\Projects']};
context.LibSetShelf('mine');
assert.match(elements.get('#LibGrid').content, /Tactile work/);
assert.match(elements.get('#LibGrid').content, /CAD only/, 'A CAD-only project still has a reachable folder card');
assert.doesNotMatch(elements.get('#LibGrid').content, /Downloaded/);
context.LibBrowseDesign({getAttribute: () => 'E:\\Projects\\Tactile'});
assert.deepEqual(paths(), [tactile.path], 'Browsing an own project includes STL without requiring Include meshes');
context.LibSetShelf('downloads');
assert.deepEqual(paths(), [downloaded.path], 'Downloaded models stay separate from own projects');
assert.equal(context.LIB.kind, 'all', 'Downloaded models must include loose meshes immediately');
context.LibSetShelf('all');
assert.equal(paths().length, 3, 'All files must include loose meshes immediately');
context.LibSetShelf('jobs');
assert.deepEqual(paths(), [alpha.path], 'Print jobs exclude own-design folders');
assert.equal(context.LibWithin('E:\\Projects\\Tactile-old\\tile.stl', 'E:\\Projects\\Tactile'), false);
context.LibUnpinDesign({getAttribute: () => 'E:\\Projects\\CAD only'});
assert.equal(context.LIB_WORKSPACE.mine.length, 1, 'Removing a shortcut only changes the workspace list');
context.LibReceive({native: true, items: [{...alpha, revision: '1', size: 40}], roots: ['E:\\Projects']});
context.LibThumbnailReceive({path: alpha.path, revision: '1', size: 40, thumbState: 'ready',
    thumb: 'preview-alpha.png', views: [{src: 'preview-alpha.png', label: 'Front'}]});
assert.equal(context.LibThumbnail(alpha).thumb, 'preview-alpha.png');
context.LibReceive({native: true, items: [{...alpha, revision: '1', size: 40, thumbState: 'pending'}], roots: ['E:\\Projects']});
assert.equal(context.LibThumbnail(alpha).thumbState, 'ready', 'Metadata refresh must preserve a completed preview for the same file revision');
context.LibReceive({native: true, items: [{...alpha, revision: '2', size: 50, thumbState: 'pending'}], roots: ['E:\\Projects']});
assert.equal(context.LibThumbnail(context.LibFindItem(alpha.path)).thumbState, 'pending', 'Changed source needs a fresh preview');
context.LibThumbnailReceive({path: alpha.path, revision: '1', size: 40, thumbState: 'ready', thumb: 'stale.png'});
assert.equal(context.LibThumbnail(context.LibFindItem(alpha.path)).thumbState, 'pending', 'Late results for an old revision must be ignored');
context.LibThumbnailReceive({path: alpha.path, revision: '2', size: 50, thumbState: 'ready', thumb: 'new.png'});
const failedImage = () => ({getAttribute: name => ({'data-thumb-path': alpha.path,
    'data-thumb-version': String(context.LIB.thumbVersions[context.LibKey(alpha.path)] || 0)})[name]});
context.LibThumbnailError(failedImage());
assert.equal(context.LibThumbnail(alpha).thumbState, 'pending', 'Missing cache image is regenerated once');
context.LibThumbnailReceive({path: alpha.path, revision: '2', size: 50, thumbState: 'ready', thumb: 'new.png'});
context.LibThumbnailError(failedImage());
assert.equal(context.LibThumbnail(alpha).thumbState, 'unavailable', 'Repeated image failure cannot loop indefinitely');
assert.equal(context.LibThumbnailSource('img/d.png'), '', 'The stock image is never a model preview');
assert.doesNotMatch(context.LibCard({...alpha, thumbState: 'unavailable'}), /src="img\/d\.png"/);
const outside = 'D:\\Downloads\\new.stl';
context.LibThumbnailReceive({path: outside, thumbState: 'ready', thumb: 'outside.png', revision: '3', size: 10});
context.LibNoteRecent([{path: outside}]);
context.LibNoteRecent([{path: outside}]);
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumb, 'outside.png', 'Replacing the recent list must retain received thumbnails');
context.LibNoteRecent([{path: outside, revision: '3', size: 10, image: 'stale-startup.png', thumbState: 'pending'}]);
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumb, 'outside.png', 'Unchanged unindexed recent fingerprint keeps the completed preview');
context.LibNoteRecent([{path: outside, revision: '4', size: 10, image: 'stale-startup.png', thumbState: 'pending'}]);
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumbState, 'pending', 'Changed recent source must hide even a startup-cached image');
assert.equal(context.LIB.thumbRequested[context.LibKey(outside)], undefined, 'Changed recent metadata clears its old request');
context.LibThumbnailReceive({path: outside, thumbState: 'ready', thumb: 'late-old.png', revision: '3', size: 10});
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumbState, 'pending', 'A late old unindexed result cannot restore a stale preview');
context.LibThumbnailReceive({path: outside, thumbState: 'ready', thumb: 'fresh-outside.png', revision: '4', size: 10});
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumb, 'fresh-outside.png');
context.LibNoteRecent([{path: outside, revision: '4', size: 11, image: 'stale-startup.png', thumbState: 'pending'}]);
assert.equal(context.LibThumbnail(context.LibSynthRecent(outside)).thumbState, 'pending', 'Changed recent size invalidates an equal-timestamp preview');
assert.equal(context.LibThumbnail(context.LibSynthRecent('Z:\\Missing.stl')).thumbState, 'pending');
assert.equal(context.LibThumbnail({path: outside, state: 'missing'}).thumbState, 'unavailable', 'A missing source cannot masquerade as a cached preview');
console.log('Project library: navigation, identity and thumbnail-state regression assertions passed.');
