// Turn each library card's thumbnail into a deck you can page through.
//
// One picture answers one question. The designer's photo says what the thing is meant to look
// like and nothing about whether the beds are packed sensibly; a plate render says the
// opposite. Both are wanted, at different moments, and neither is worth opening the slicer
// for. So the thumbnail holds every picture of the project and steps between them.
//
// This attaches to cards after they are rendered rather than being part of the card template.
// The card is built by LibCard() in library.js; reaching into that couples two features that
// change for different reasons, and a card that fails to render because its image list is
// malformed is worse than a card with one picture. Enhancement that can be skipped degrades
// to exactly the behaviour that existed before it.
//
// Image sets come from build_views.js, generated by E:\3D-Printing\Scripts\build_views.py.

var SLIDE_STATE = {};      // card path -> index, so paging survives a re-render

function SlideImages(path) {
    // Native image sets carry the file revision, so a regenerated thumbnail replaces its cache.
    if (typeof PROJECT_LIBRARY !== 'undefined' && PROJECT_LIBRARY.native) {
        var info = LibThumbnail(LibFindItem(path));
        var views = info.thumbState === 'ready' ? info.views : [];
        return views && views.length > 1 ? views : null;
    }
    if (typeof PROJECT_VIEWS === 'undefined') return null;
    var imgs = (PROJECT_VIEWS[path] || []).filter(function (view) { return view && LibThumbnailSource(view.src); });
    return (imgs && imgs.length > 1) ? imgs : null;
}

function SlideShow(card, idx) {
    var path = card.getAttribute('fpath');
    var imgs = SlideImages(path);
    if (!imgs) return;

    var n = imgs.length;
    idx = ((idx % n) + n) % n;          // wrap both ways
    SLIDE_STATE[path] = idx;

    var img = card.querySelector('.LibThumb img');
    if (img) {
        img.src = imgs[idx].src;
        // An SVG plate view is a drawing on a transparent ground, and `contain` letterboxes
        // it correctly; a photo wants the same treatment, so nothing special is needed here.
        img.setAttribute('alt', 'Preview of ' + LibFindItem(path).name + (imgs[idx].label ? ': ' + imgs[idx].label : ''));
    }
    var label = card.querySelector('.SlideLabel');
    if (label) label.textContent = imgs[idx].label + '  ' + (idx + 1) + '/' + n;

    var dots = card.querySelectorAll('.SlideDot');
    for (var i = 0; i < dots.length; i++) {
        dots[i].className = 'SlideDot' + (i === idx ? ' SlideDotOn' : '');
    }
}

function SlideStep(el, delta, ev) {
    // The arrows sit inside the card, and the card opens the project when clicked. Without
    // this the first arrow press launches the slicer.
    if (ev) { ev.stopPropagation(); ev.preventDefault(); }
    var card = el.closest ? el.closest('.LibCard') : null;
    if (!card) return;
    var path = card.getAttribute('fpath');
    SlideShow(card, (SLIDE_STATE[path] || 0) + delta);
}

function SlideEnhance(card) {
    if (card.getAttribute('data-slides') === '1') return;
    var imgs = SlideImages(card.getAttribute('fpath'));
    if (!imgs) return;
    card.setAttribute('data-slides', '1');

    var thumb = card.querySelector('.LibThumb');
    if (!thumb) return;

    var dots = '';
    for (var i = 0; i < imgs.length && i < 12; i++) dots += '<i class="SlideDot"></i>';

    var nav = document.createElement('div');
    nav.className = 'SlideNav';
    nav.innerHTML =
        '<button class="SlideArrow SlideLeft" title="Previous view">&#8249;</button>' +
        '<button class="SlideArrow SlideRight" title="Next view">&#8250;</button>' +
        '<div class="SlideDots">' + dots + '</div>' +
        '<div class="SlideLabel"></div>';
    thumb.appendChild(nav);

    nav.querySelector('.SlideLeft').addEventListener('click', function (e) {
        SlideStep(this, -1, e);
    });
    nav.querySelector('.SlideRight').addEventListener('click', function (e) {
        SlideStep(this, 1, e);
    });
    var dotEls = nav.querySelectorAll('.SlideDot');
    for (var d = 0; d < dotEls.length; d++) {
        (function (j) {
            dotEls[j].addEventListener('click', function (e) {
                e.stopPropagation();
                SlideShow(card, j);
            });
        })(d);
    }

    SlideShow(card, SLIDE_STATE[card.getAttribute('fpath')] || 0);
}

function SlideEnhanceAll() {
    var cards = document.querySelectorAll('#LibGrid .LibCard');
    for (var i = 0; i < cards.length; i++) SlideEnhance(cards[i]);
}

function SlideRefresh(card) {
    var nav = card.querySelector('.SlideNav');
    if (nav) nav.remove();
    card.removeAttribute('data-slides');
    SlideEnhance(card);
}

// The grid is rebuilt on every filter change, search keystroke and page. Watching it is what
// makes this independent of the render path: no hook to add, nothing to keep in step.
function SlideInit() {
    var grid = document.getElementById('LibGrid');
    if (!grid) return;
    SlideEnhanceAll();
    if (window.MutationObserver) {
        new MutationObserver(function () { SlideEnhanceAll(); })
            .observe(grid, { childList: true });
    }
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', SlideInit);
} else {
    SlideInit();
}
