#ifndef slic3r_GUI_PodBanner_hpp_
#define slic3r_GUI_PodBanner_hpp_

#include <wx/dc.h>
#include <wx/gdicmn.h>

//The one banner ground for Podslicer chrome: gunmetal PEI (resources/images/
//gunmetal_pei.png, regenerated by tools/gen_gunmetal.py), tiled across any rect.
//Callers pass their own mode decision as `enabled` (a surface that is dark in both
//colour modes passes true outright); a false return means "not drawn" and the
//caller keeps its flat fill, so a missing asset degrades honestly.
//Global namespace, like the rest of Widgets.
class PodBanner
{
public:
    //phase_x is the caller's own x-offset within a textured parent, so the grain
    //runs continuously across the boundary instead of restarting at the child's edge.
    static bool draw(wxDC &dc, const wxRect &rect, bool enabled, int phase_x = 0);
};

#endif // slic3r_GUI_PodBanner_hpp_
